services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    command: azurite-blob --blobHost 0.0.0.0 --location /data --skipApiVersionCheck
    ports:
      - "10000:10000"
    volumes:
      - ./.azurite:/data
